general:
  lr2: 0.01
  wd2: 0.0001
  epoch: 0
  epoch1: 100
  epoch2: 10000
  decay_epoch: 1000
Computers:
  learning_rate: 0.0001
  output_dim: 256
  num_proj_dim: 256
  activation: 'relu'
  gnn_type: 'GAT'
  num_layers: 2
  drop_edge_rate: 0.4
  drop_feature_rate: 0.1
  tau: 0.5
  num_epochs: 1000
  weight_decay: 0
  lr2: 0.01
  wd2: 0.000001
  epoch: 0
  epoch1: 100
  epoch2: 10000
  decay_epoch: 1000
Cora:
  learning_rate: 0.0001
  output_dim: 256
  num_proj_dim: 256
  activation: 'relu'
  gnn_type: 'GAT'
  num_layers: 2
  drop_edge_rate: 0.4
  drop_feature_rate: 0.1
  tau: 0.5
  num_epochs: 1000
  weight_decay: 0
  lr2: 0.01
  wd2: 0.00001
  epoch: 0
  epoch1: 100
  epoch2: 10000
  decay_epoch: 1000
PubMed:
  learning_rate: 0.0001
  output_dim: 256
  num_proj_dim: 256
  activation: 'relu'
  gnn_type: 'GAT'
  num_layers: 2
  drop_edge_rate: 0.4
  drop_feature_rate: 0.1
  tau: 0.5
  num_epochs: 1000
  weight_decay: 0
  lr2: 0.01
  wd2: 0.00001
  epoch: 0
  epoch1: 100
  epoch2: 10000
  decay_epoch: 1000
CiteSeer:
  learning_rate: 0.0001
  output_dim: 256
  num_proj_dim: 256
  activation: 'relu'
  gnn_type: 'GAT'
  num_layers: 2
  drop_edge_rate: 0.4
  drop_feature_rate: 0.1
  tau: 0.5
  num_epochs: 1000
  weight_decay: 0
  lr2: 0.01
  wd2: 0.00001
  epoch: 0
  epoch1: 100
  epoch2: 10000
  decay_epoch: 1000
Photo:
  learning_rate: 0.0001
  output_dim: 256
  num_proj_dim: 256
  activation: 'relu'
  gnn_type: 'GAT'
  num_layers: 2
  drop_edge_rate: 0.4
  drop_feature_rate: 0.1
  tau: 0.5
  num_epochs: 1000
  weight_decay: 0
  lr2: 0.01
  wd2: 0.00001
  epoch: 0
  epoch1: 100
  epoch2: 10000
  decay_epoch: 1000
transfer:
  hidden_dim: 64
  output_dim: 256
  activation: 'relu'
  gnn_type: 'GAT'
  num_layers: 2
  learning_rate: 0.001
  weight_decay: 0
  epoch: 0
  epoch1: 100
  epoch2: 10000
  decay_epoch: 1000
  b1: 0.5
  b2: 0.999
  batch_size: 128
  lambda_cyc: 15
  lambda_anc: 5
  lambda_cos: 0
  lambda_dis: 5
  lambda_str: 0
  lambda_map: 5
  lambda_id: 5
  checkpoint_interval: 10
  lr2: 0.01
  wd2: 0.000001

